### ISSUE TITLE
Potential Feature: Animations from Sim Archives

### ISSUE THREAD

**Issue by Rmelikyan** [hannorein/rebound-blender#1]
Hi Hanno,

This is a super cool project! 

I have no experience in blender myself, but I'm happy to see REBOUND sims being visualized in such a sophisticated software.

Is it possible to draft a similar example that uses Sim Archives or even develop it into a generalized plug and play script that would work for most data sets?

Since archive snapshots can be many many years apart, this may not have particular value for sims with large time ranges... but there's got to be some use case right? (Maybe a new rebound archive type that specifically collects data necessary for visualization at some minimum temporal resolution?)

Anyway, these are just a thoughts in response to the door you've opened with this project.

Keep it up!

-Robert

**Comment by hannorein** [comment]
Hi Robert, 

Yes! You can use almost the exact same script as in the first example. At the very bottom of the script, just step through a simulation archive instead of integrating the simulation. I'll try to add a few more examples in the future!

Hanno

**Comment by Rmelikyan** [comment]
Great! 

I'm looking forward to a moment when I can try to convert some of my projects work into beautiful animation!
